version: '3'
services:
  web1:
    image: nginx
    volumes:
     - ./vhost1.conf:/etc/nginx/conf.d/default.conf
     - ./chall1:/usr/share/nginx/html/chall1
    ports:
     - "8081:80"
  web2:
    image: nginx
    volumes:
     - ./vhost2.conf:/etc/nginx/conf.d/default.conf
     - ./chall2:/usr/share/nginx/html/chall2
    ports:
     - "8082:80"
